from django.urls import path, include
from .views import (ProductViewSet, ReceiptViewSet, DeliveryViewSet, InternalTransferViewSet,
                    PhysicalInventoryViewSet, ScrapViewSet, LandedCostViewSet, ProductAttributeViewSet,
                    UnitOfMeasureCategoryViewSet, ProductPackagingViewSet, ReorderingRuleViewSet,
                    BarcodeNomenclatureViewSet)

urlpatterns = [
    path('products/create/', ProductViewSet.as_view({'post': 'create_product'}), name='create-product'),
    path('products/', ProductViewSet.as_view({'get': 'get_products'}), name='get-products'),
    path('products/update/<int:pk>/', ProductViewSet.as_view({'put': 'update_product'}), name='update-product'),
    path('products/delete/<int:pk>/', ProductViewSet.as_view({'delete': 'delete_product'}), name='delete-product'),
    path('products/createpc/', ProductViewSet.as_view({'post': 'create_product_category'}), name='create-pc'),
    path('products/getpc/', ProductViewSet.as_view({'get': 'get_product_categories'}), name='get-pc'),
    path('products/updatepc/<uuid:pk>/', ProductViewSet.as_view({'put': 'update_product_category'}), name='update-pc'),
    path('products/deletepc/<uuid:pk>/', ProductViewSet.as_view({'delete': 'delete_product_category'}), name='delete-pc'),
    path('products/createtemplate/', ProductViewSet.as_view({'post': 'create_product_template'}), name='create-template'),
    path('products/gettemplate/', ProductViewSet.as_view({'get': 'get_product_templates'}), name='get-template'),
    path('products/replenish/', ProductViewSet.as_view({'post': 'replenish'}), name='replenish-order'),
    path('products/purchase/', ProductViewSet.as_view({'post': 'purchase'}), name='purchase-order'),
    path('products/inventory/', ProductViewSet.as_view({'get': 'inventory', 'post': 'inventory'}), name='inventory'),
    path('receipts/create/', ReceiptViewSet.as_view({'post': 'create_receipt'}), name='create-receipt'),
    path('receipts/', ReceiptViewSet.as_view({'get': 'get_receipts'}), name='get-receipts'),
    path('receipts/update/<int:pk>/', ReceiptViewSet.as_view({'put': 'update_receipt'}), name='update-receipt'),
    path('receipts/delete/<int:pk>/', ReceiptViewSet.as_view({'delete': 'delete_receipt'}), name='delete-receipt'),
    path('deliveries/create/', DeliveryViewSet.as_view({'post': 'create_delivery'}), name='create-delivery'),
    path('deliveries/', DeliveryViewSet.as_view({'get': 'get_deliveries'}), name='get-deliveries'),
    path('deliveries/update/<int:pk>/', DeliveryViewSet.as_view({'put': 'update_delivery'}), name='update-delivery'),
    path('deliveries/delete/<int:pk>/', DeliveryViewSet.as_view({'delete': 'delete_delivery'}), name='delete-delivery'),
    path('internal-transfers/create/', InternalTransferViewSet.as_view({'post': 'create_internal_transfer'}), name='create-internal-transfer'),
    path('internal-transfers/', InternalTransferViewSet.as_view({'get': 'get_internal_transfers'}), name='get-internal-transfers'),
    path('internal-transfers/update/<int:pk>/', InternalTransferViewSet.as_view({'put': 'update_internal_transfer'}), name='update-internal-transfer'),
    path('internal-transfers/delete/<int:pk>/', InternalTransferViewSet.as_view({'delete': 'delete_internal_transfer'}), name='delete-internal-transfer'),
    path('physical-inventory/create/', PhysicalInventoryViewSet.as_view({'post': 'create_physical_inventory'}), name='create-physical-inventory'),
    path('physical-inventory/', PhysicalInventoryViewSet.as_view({'get': 'get_physical_inventories'}), name='get-physical-inventories'),
    path('physical-inventory/update/<int:pk>/', PhysicalInventoryViewSet.as_view({'put': 'update_physical_inventory'}), name='update-physical-inventory'),
    path('physical-inventory/delete/<int:pk>/', PhysicalInventoryViewSet.as_view({'delete': 'delete_physical_inventory'}), name='delete-physical-inventory'),
    path('scrap/create/', ScrapViewSet.as_view({'post': 'create_scrap'}), name='create-scrap'),
    path('scrap/', ScrapViewSet.as_view({'get': 'get_scraps'}), name='get-scraps'),
    path('scrap/update/<uuid:pk>/', ScrapViewSet.as_view({'put': 'update_scrap'}), name='update-scrap'),
    path('scrap/delete/<uuid:pk>/', ScrapViewSet.as_view({'delete': 'delete_scrap'}), name='delete-scrap'),
    path('landed-costs/create/', LandedCostViewSet.as_view({'post': 'create_landed_cost'}), name='create-landed-cost'),
    path('landed-costs/get/', LandedCostViewSet.as_view({'get': 'get_landed_costs'}), name='get-landed-costs'),
    path('landed-costs/update/<uuid:pk>/', LandedCostViewSet.as_view({'put': 'update_landed_cost'}), name='update-landed-cost'),
    path('landed-costs/delete/<uuid:pk>/', LandedCostViewSet.as_view({'delete': 'delete_landed_cost'}), name='delete-landed-cost'),
    path('productAttribute/create/', ProductAttributeViewSet.as_view({'post': 'create_product_attribute'}), name='create-product-attribute'),
    path('productAttribute/get/', ProductAttributeViewSet.as_view({'get': 'get_product_attributes'}), name='get-product-attribute'),
    path('productAttribute/update/<uuid:pk>/', ProductAttributeViewSet.as_view({'put': 'update_product_attribute'}), name='update-product-attribute'),
    path('productAttribute/delete/<uuid:pk>/', ProductAttributeViewSet.as_view({'delete': 'delete_product_attribute'}), name='delete-product-attribute'),
    path('UoM/create/', UnitOfMeasureCategoryViewSet.as_view({'post': 'create_unit_of_measure_category'}), name='create-UoM'),
    path('UoM/get/', UnitOfMeasureCategoryViewSet.as_view({'get': 'get_unit_of_measure_categories'}), name='get-UoM'),
    path('UoM/update/<uuid:pk>/', UnitOfMeasureCategoryViewSet.as_view({'put': 'update_unit_of_measure_category'}), name='update-UoM'),
    path('UoM/delete/<uuid:pk>/', UnitOfMeasureCategoryViewSet.as_view({'delete': 'delete_unit_of_measure_category'}), name='delete-UoM'),
    path('productpackaging/create/', ProductPackagingViewSet.as_view({'post': 'create_product_packaging'}), name='create-pp'),
    path('productpackaging/get/', ProductPackagingViewSet.as_view({'get': 'get_product_packaging'}), name='get-pp'),
    path('productpackaging/update/<uuid:pk>/', ProductPackagingViewSet.as_view({'put': 'update_product_packaging'}), name='update-pp'),
    path('productpackaging/delete/<uuid:pk>/', ProductPackagingViewSet.as_view({'delete': 'delete_product_packaging'}), name='delete-pp'),
    path('rrv/create/', ReorderingRuleViewSet.as_view({'post': 'create_reordering_rule'}), name='create-rrv'),
    path('rrv/get/', ReorderingRuleViewSet.as_view({'get': 'get_reordering_rules'}), name='get-rrv'),
    path('rrv/update/<uuid:pk>/', ReorderingRuleViewSet.as_view({'put': 'update_reordering_rule'}), name='update-rrv'),
    path('rrv/delete/<uuid:pk>/', ReorderingRuleViewSet.as_view({'delete': 'delete_reordering_rule'}), name='delete-rrv'),
    path('bcn/create/', BarcodeNomenclatureViewSet.as_view({'post': 'create_barcode_nomenclature'}), name='create-bcn'),
    path('bcn/get/', BarcodeNomenclatureViewSet.as_view({'get': 'get_barcode_nomenclatures'}), name='get-bcn'),
    path('bcn/update/<uuid:pk>/', BarcodeNomenclatureViewSet.as_view({'put': 'update_barcode_nomenclature'}), name='update-bcn'),
    path('bcn/delete/<uuid:pk>/', BarcodeNomenclatureViewSet.as_view({'delete': 'delete_barcode_nomenclature'}), name='delete-bcn'),
]