# Generated by Django 5.0.6 on 2024-07-16 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authorisation', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('direct_unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allow_invoice_discount', models.BooleanField(default=False)),
                ('vat_identifier', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_reference', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('order_deadline', models.DateField()),
                ('expected_arrival', models.DateField()),
                ('deliver_to', models.CharField(max_length=255)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_excluded', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authorisation.company')),
            ],
        ),
        migrations.CreateModel(
            name='RFQProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authorisation.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purchase.requestforquotation')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_street1', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_street2', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_state', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_country', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('job_position', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authorisation.company')),
            ],
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('expected_arrival', models.DateField()),
                ('currency', models.CharField(max_length=120)),
                ('purchase_order_no', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_less_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.CharField(max_length=5)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=True, editable=False, max_digits=10, null=True)),
                ('company', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='Authorisation.company')),
                ('products', models.ManyToManyField(related_name='purchase_orders', to='purchase.purchaseorderproduct')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchase.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authorisation.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_price_lists', to='Inventory.product')),
            ],
        ),
    ]
